### ISSUE TITLE
missing images for amd64

### ISSUE THREAD

**Issue by markymarrow** [rhasson/iceberg_workshop#1]
Thanks for the workshop at Chill Data Summit yesterday, it was very useful.

Although I couldn't participate properly to begin with, which appears to be because the images for spark and polaris were built for arm64 only - so the Apple Silicon Mac users were fine but those of us using an intel based laptop were not.

While I could rebuild the spark image for amd64, the build directory for polaris (polaris_src) does not exist in the repository (I did eventually find my way here https://github.com/apache/polaris and built a container)

However, it would have been useful if there were multi-platform images for both of these containers, which could have been created using something like the following
```
docker buildx create --use
docker buildx bake -f docker-compose.yml --set *.platform=linux/amd64,linux/arm64 --push
```

**Comment by rhasson** [comment]
@markymarrow I'm really sorry that I didn't catch this in advance and was able to get you up and running during the workshop. It's a big miss on my part.  

I appreciate you finding the root cause and sharing the details with me.  I'm working on rebuilding the images with a few changes and multiple platforms.

And yes, the /polaris_src/ folder is basically a clone of the polaris repo if you wanted to build it from source since a docker image wasn't available.  I'm sure there is a more elegant way to handle this but I ran out of time :( I'll find a way to streamline this as well.

**Comment by rhasson** [comment]
Rebuilt the [Polaris](https://hub.docker.com/repository/docker/rhasson/polaris/general) and [Spark](https://hub.docker.com/repository/docker/rhasson/spark/general) containers for linux/arm64 and linux/amd64 platforms and pushed to docker hub.
